### ISSUE TITLE
Change email service

### ISSUE THREAD

**Issue by rpmjade** [rpmsoftware/coast-guard#8] opened 2018-05-23 14:46 UTC
Gmail has been blocking access to Coast Guard lately. I have gone in and said that logon attempt was valid and the account has the setting "Allow less secure apps: ON". I'm not sure what else we can do. To discuss when you are back from vacation. In the meantime George will be acting as a manual Coast Guard replacement.

FYI @jeremyrpm

**Comment by jwindmuller** [comment] 2019-03-13 16:11
Duplicate of #12

**Comment by jwindmuller** [comment] 2019-06-07 17:05
This doesn't seem to be as necessary after switching to the Gmail API in #12

**Closed by jwindmuller** 2019-06-07 17:05 UTC
